//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Rating1 { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
