//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public double Price { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string ImagePath { get; set; }
        public string Name { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
